version: '3'
services:
  backend:
    image: nginx:latest
    ports:
      - 8090:80
    environment:
      - NGINX_HOST=backend
  varnish:
    environment:
      - VARNISH_VCL_CONF=/etc/varnish/default.vcl
    env_file:
      - ./varnish.env
    image: mondiamedia/varnish
    ports:
      - 80:6081
    volumes:
      - ./varnish.env:/etc/varnish/varnish.params
      - ./default.vcl:/etc/varnish/default.vcl